/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for Ultrasonic Sensot
 *
 * Author: Mazen Hekal
 *
 *******************************************************************************/

#include"ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <avr/io.h>
#include <util/delay.h>
#include "lcd.h"
#include <math.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeValue = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * 1. Initialize the ICU driver as required.
 * 2.Setup the ICU call back function.
 * 3.Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void ULTRASONIC_init(void)
{
	/* Initialize ICU Driver with Prescalar of F_CPU_8 and rising edge detection type */
	ICU_ConfigType ICU_config = {ICU_F_CPU_PRESCALAR,ICU_FIRST_DETECTION_EDGE};
	ICU_init(&ICU_config);
	/* Enable Global Interrupt I-Bit */
	SREG |= (1<<7);
	/* Setup the ICU call back function */
	ICU_setCallBack(ULTRASONIC_edgeProcessing);
	/* Set Trigger PIN as output pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void ULTRASONIC_trigger(void)
{
	/* Transmit 10 us trigger pulse to trigger pin in ultrasonic */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * 1.Send the trigger pulse by using ULTRASONIC_trigger function.
 * 2.Start the measurements by the ICU from this moment.
 */
uint16 ULTRASONIC_readDistance(void)
{
	uint16 distance;
	/* Send the trigger pulse */
	ULTRASONIC_trigger();
	/* calculate distance
	 * Note : Added 1 to round up the number
	 */
	distance = (uint16)((uint32)(g_timeValue * (SPEED_SOUND_CM_S/2))\
			/((uint32)F_CPU/ICU_F_CPU_PRESCALAR_VALUE)) + 1;
	return distance;
}

/*
 * Description :
 * 1.This is the call back function called by the ICU driver.
 * 2.This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void ULTRASONIC_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/* Clear the timer counter */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Get Timer Value */
		g_timeValue = ICU_getInputCaptureValue();
		/* Clear the timer counter */
		ICU_clearTimerValue();
		g_edgeCount = 0;
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RISING);
	}
}




